### ISSUE TITLE
Tooltip, errors en warnings

### ISSUE THREAD

**Issue by quintende** [TomDobbelaere/PhotoWeave#61]

**Comment by LiamDobbelaere** [comment]
- [ ] Tooltips on almost everything
- [x] ~~Warning when going to manual binding assignment because all bindings will be erased~~ (not needed)
- [x] Warning when image is too large and may appear blurry

**Comment by LiamDobbelaere** [comment]
- [x] Warning when rescaling -> selections will be cleared
- [x] Warning when changing posterization -> bindings will be lost

**Comment by LiamDobbelaere** [comment]
Done, see #93
