### ISSUE TITLE
Optie om een vierkantig/rechthoekige selectie te maken.

### ISSUE THREAD

**Issue by quintende** [TomDobbelaere/PhotoWeave#98]
Met de touchpad glitched de vrije selectie wel regelmatig 😢 , Dus de kans is groot dat een leek deze problemen ook zou tegen komen.
Sinds dat het programma gebruiksvriendelijk voor een leek moet zijn.

**Comment by LiamDobbelaere** [comment]
:angry:

**Comment by LiamDobbelaere** [comment]
Scope too big to fix for release, just use a fucking mouse or get good
